manala:
  repository: /Users/loic/Ops/manala-recipes
  recipe: dev.python

repository_save: /Users/loic/Ops/manala-recipes


vagrant: 
  project_name: src-ctt-client
  box: loic-roux-404/deb64-buster
  box_update: false
  box_version: 3.10.4
  vb_guest_update: false
  domain: ply.ctt.test
  git: 
    org: g4-dev
    provider: github.com
  paths: 
    guest: /home/vagrant/trained_deepspeech/exploit-project
    host: ./
    web: ""
  network: 
    dns: true
    ip: 192.68.11.11
    ports: []
    ssl:
        cert: null
        path: /etc/ssl
    type: private 
  ansible: 
    disabled: false
    inventory: inventory
    playbook: playbook-ctt-client
    playbook_version: master
    sub_playbook: site.yml
    type: local
    vars:
        keyboard_mac: false
  fs: 
    opts:
        disabled: true
        ignored:
          - /**/.DS_Store
          - .git
          - .vagrant
          - .idea/
          - .vscode/
        rsync_auto: true
        smb_password: null
        smb_username: null
    type: rsync
  provider:  
    opts:
        cpus: "2"
        memory: "1024"
        natdnshostresolver1: on
    type: virtualbox
